"""sync_models

Revision ID: d359b5faf4ed
Revises: 20260621_phase7
Create Date: 2026-07-07 19:06:19.269020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd359b5faf4ed'
down_revision: Union[str, None] = '20260621_phase7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_organization_id')
        batch_op.drop_index('ix_audit_logs_resource_id')
        batch_op.drop_index('ix_audit_logs_resource_type')

    op.drop_table('audit_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_is_read')
        batch_op.drop_index('ix_notifications_organization_id')
        batch_op.drop_index('ix_notifications_user_id')

    op.drop_table('notifications')
    with op.batch_alter_table('billing_contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_contracts_client_organization_id')
        batch_op.drop_index('ix_billing_contracts_organization_id')

    op.drop_table('billing_contracts')
    with op.batch_alter_table('task_time_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_task_time_logs_task_id')
        batch_op.drop_index('ix_task_time_logs_user_id')

    op.drop_table('task_time_logs')
    with op.batch_alter_table('event_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_event_outbox_event_type')
        batch_op.drop_index('ix_event_outbox_organization_id')
        batch_op.drop_index('ix_event_outbox_processed')
        batch_op.drop_index('ix_event_outbox_user_id')

    op.drop_table('event_outbox')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_organization_id')
        batch_op.drop_index('ix_attachments_status')

    op.drop_table('attachments')
    with op.batch_alter_table('sso_configurations', schema=None) as batch_op:
        batch_op.drop_index('ix_sso_configurations_email_domain')
        batch_op.drop_index('ix_sso_configurations_organization_id')

    op.drop_table('sso_configurations')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_security_events_organization_id')

    op.drop_table('security_events')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_invoice_number')
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_unique_constraint('uq_invoice_org_number', ['organization_id', 'invoice_number'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_memberships_invite_token'), ['invite_token'], unique=True)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('uq_password_reset_tokens_token_hash', type_='unique')
        batch_op.drop_index('ix_password_reset_tokens_token_hash')
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(), nullable=True))
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('_mfa_secret')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_mfa_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('mfa_secret')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_column('version')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.create_index('ix_password_reset_tokens_token_hash', ['token_hash'], unique=False)
        batch_op.create_unique_constraint('uq_password_reset_tokens_token_hash', ['token_hash'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_invite_token'))
        batch_op.drop_column('invite_token')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_organization_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_org_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.create_index('ix_invoices_invoice_number', ['invoice_number'], unique=True)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_organization_id'))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))

    op.create_table('security_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='security_events_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='security_events_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='security_events_pkey')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('ix_security_events_organization_id', ['organization_id'], unique=False)

    op.create_table('sso_configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='Provider type: "saml" or "oidc"'),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='IdP Entity ID (SAML) or Client ID (OIDC)'),
    sa.Column('metadata_url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='IdP metadata URL for auto-configuration'),
    sa.Column('sso_url', sa.VARCHAR(), autoincrement=False, nullable=False, comment='IdP login / authorization endpoint URL'),
    sa.Column('certificate', sa.TEXT(), autoincrement=False, nullable=True, comment='PEM-encoded certificate for SAML signature validation'),
    sa.Column('client_secret_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Encrypted OIDC client secret (Fernet, versioned)'),
    sa.Column('default_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_domain', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Email domain to match for this SSO config (e.g. "acme.com")'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], name='sso_configurations_default_role_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='sso_configurations_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sso_configurations_pkey'),
    sa.UniqueConstraint('email_domain', name='uq_sso_configurations_email_domain')
    )
    with op.batch_alter_table('sso_configurations', schema=None) as batch_op:
        batch_op.create_index('ix_sso_configurations_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_sso_configurations_email_domain', ['email_domain'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'quarantined'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='attachments_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='attachments_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='attachments_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='attachments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_status', ['status'], unique=False)
        batch_op.create_index('ix_attachments_organization_id', ['organization_id'], unique=False)

    op.create_table('event_outbox',
    sa.Column('event_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='event_outbox_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_outbox_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id', name='uq_event_outbox_event_id')
    )
    with op.batch_alter_table('event_outbox', schema=None) as batch_op:
        batch_op.create_index('ix_event_outbox_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_event_outbox_processed', ['processed'], unique=False)
        batch_op.create_index('ix_event_outbox_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_event_outbox_event_type', ['event_type'], unique=False)

    op.create_table('task_time_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_time_logs_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='task_time_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='task_time_logs_pkey')
    )
    with op.batch_alter_table('task_time_logs', schema=None) as batch_op:
        batch_op.create_index('ix_task_time_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_task_time_logs_task_id', ['task_id'], unique=False)

    op.create_table('billing_contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('billing_cycle_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('billing_cycle_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_organization_id'], ['organizations.id'], name='billing_contracts_client_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='billing_contracts_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='billing_contracts_pkey')
    )
    with op.batch_alter_table('billing_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_billing_contracts_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_billing_contracts_client_organization_id', ['client_organization_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='notifications_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_notifications_is_read', ['is_read'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_api_key_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_before_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_after_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_resource_type', ['resource_type'], unique=False)
        batch_op.create_index('ix_audit_logs_resource_id', ['resource_id'], unique=False)
        batch_op.create_index('ix_audit_logs_organization_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
